backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Published By", name: "author", widget: "string", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - label: "Content Type"
        name: "content_type"
        widget: "select"
        options:
          - { label: "Markdown Body", value: "body" }
          - { label: "PDF File", value: "pdf" }
        default: "body"
      - {label: "Body", name: "body", widget: "markdown", required: false, hint: "Write your blog post here."}
      - {label: "PDF File", name: "pdf", widget: "file", required: false, media_library: {allow_multiple: false}, hint: "Upload a PDF file if you want to use PDF instead of body."}

  - name: "cv"
    label: "CV"
    files:
      - file: "content/cv.md"
        label: "Upload CV"
        name: "cv"
        fields:
          - {label: "CV File", name: "cv_file", widget: "file", media_library: {allow_multiple: false}, required: true}
